"""style_guides listing_drafts listings

Revision ID: 10a78b7c40ad
Revises: 32adc070ffb3
Create Date: 2026-08-09 11:31:05.634710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10a78b7c40ad'
down_revision: Union[str, Sequence[str], None] = '32adc070ffb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_drafts',
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disclosure_seller', sa.String(length=120), nullable=False),
    sa.Column('disclosure_tools', sa.Text(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_index(op.f('ix_listing_drafts_asset_id'), 'listing_drafts', ['asset_id'], unique=True)
    op.create_index(op.f('ix_listing_drafts_created_at'), 'listing_drafts', ['created_at'], unique=False)
    op.create_table('listings',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('channel_name', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_asset_id'), 'listings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_listings_channel_name'), 'listings', ['channel_name'], unique=False)
    op.create_index(op.f('ix_listings_created_at'), 'listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_listings_draft_id'), 'listings', ['draft_id'], unique=True)
    op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_listings_state'), 'listings', ['state'], unique=False)
    op.create_table('style_guides',
    sa.Column('style_guide_id', sa.Uuid(), nullable=False),
    sa.Column('niche_keyword', sa.String(length=200), nullable=False),
    sa.Column('template', sa.String(length=2000), nullable=False),
    sa.Column('variations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('style_guide_id')
    )
    op.create_index(op.f('ix_style_guides_created_at'), 'style_guides', ['created_at'], unique=False)
    op.create_index(op.f('ix_style_guides_niche_keyword'), 'style_guides', ['niche_keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_guides_niche_keyword'), table_name='style_guides')
    op.drop_index(op.f('ix_style_guides_created_at'), table_name='style_guides')
    op.drop_table('style_guides')
    op.drop_index(op.f('ix_listings_state'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_draft_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_created_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_channel_name'), table_name='listings')
    op.drop_index(op.f('ix_listings_asset_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_listing_drafts_created_at'), table_name='listing_drafts')
    op.drop_index(op.f('ix_listing_drafts_asset_id'), table_name='listing_drafts')
    op.drop_table('listing_drafts')
    # ### end Alembic commands ###
