"""cost_events

Revision ID: 32adc070ffb3
Revises: 617479e3387b
Create Date: 2026-08-09 09:23:37.037657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32adc070ffb3"
down_revision: Union[str, Sequence[str], None] = "617479e3387b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_events",
        sa.Column("cost_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cost_id"),
    )
    op.create_index(op.f("ix_cost_events_category"), "cost_events", ["category"], unique=False)
    op.create_index(
        op.f("ix_cost_events_occurred_at"), "cost_events", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_cost_events_occurred_category", "cost_events", ["occurred_at", "category"], unique=False
    )
    op.create_index(op.f("ix_cost_events_reference"), "cost_events", ["reference"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cost_events_reference"), table_name="cost_events")
    op.drop_index("ix_cost_events_occurred_category", table_name="cost_events")
    op.drop_index(op.f("ix_cost_events_occurred_at"), table_name="cost_events")
    op.drop_index(op.f("ix_cost_events_category"), table_name="cost_events")
    op.drop_table("cost_events")
    # ### end Alembic commands ###
