"""generated_assets

Revision ID: 617479e3387b
Revises: d012c10a0065
Create Date: 2026-08-08 21:08:26.670222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "617479e3387b"
down_revision: Union[str, Sequence[str], None] = "d012c10a0065"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_assets",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("niche_keyword", sa.String(length=200), nullable=False),
        sa.Column("variant_index", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("failure", sa.String(length=24), nullable=True),
        sa.Column("cost_amount", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("print_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delivery_files", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_generated_assets_created_at"), "generated_assets", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_generated_assets_niche_keyword"),
        "generated_assets",
        ["niche_keyword"],
        unique=False,
    )
    op.create_index(op.f("ix_generated_assets_stage"), "generated_assets", ["stage"], unique=False)
    op.create_index(
        "ix_generated_assets_stage_failure", "generated_assets", ["stage", "failure"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_generated_assets_stage_failure", table_name="generated_assets")
    op.drop_index(op.f("ix_generated_assets_stage"), table_name="generated_assets")
    op.drop_index(op.f("ix_generated_assets_niche_keyword"), table_name="generated_assets")
    op.drop_index(op.f("ix_generated_assets_created_at"), table_name="generated_assets")
    op.drop_table("generated_assets")
    # ### end Alembic commands ###
