"""trend_signals

Revision ID: 6c65720cb496
Revises: 117dac0d6a22
Create Date: 2026-08-02 19:25:10.373946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c65720cb496"
down_revision: Union[str, Sequence[str], None] = "117dac0d6a22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trend_signals",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("search_volume", sa.Integer(), nullable=False),
        sa.Column("volume_scale", sa.String(length=16), nullable=False),
        sa.Column("competition_score", sa.Integer(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_index(
        op.f("ix_trend_signals_collected_at"), "trend_signals", ["collected_at"], unique=False
    )
    op.create_index(op.f("ix_trend_signals_keyword"), "trend_signals", ["keyword"], unique=False)
    op.create_index(op.f("ix_trend_signals_platform"), "trend_signals", ["platform"], unique=False)
    op.create_index(
        "ix_trend_signals_platform_keyword_collected",
        "trend_signals",
        ["platform", "keyword", "collected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trend_signals_platform_keyword_collected", table_name="trend_signals")
    op.drop_index(op.f("ix_trend_signals_platform"), table_name="trend_signals")
    op.drop_index(op.f("ix_trend_signals_keyword"), table_name="trend_signals")
    op.drop_index(op.f("ix_trend_signals_collected_at"), table_name="trend_signals")
    op.drop_table("trend_signals")
    # ### end Alembic commands ###
