"""review_decisions

Revision ID: d012c10a0065
Revises: fd327ec3a132
Create Date: 2026-08-08 20:50:03.990259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d012c10a0065"
down_revision: Union[str, Sequence[str], None] = "fd327ec3a132"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_decisions",
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer", sa.String(length=120), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=32), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("ip_checks_cleared", postgresql.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("screened_by", sa.String(length=120), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index(
        "ix_review_decisions_asset_approved",
        "review_decisions",
        ["asset_id", "approved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_decisions_asset_id"), "review_decisions", ["asset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_decisions_asset_id"), table_name="review_decisions")
    op.drop_index("ix_review_decisions_asset_approved", table_name="review_decisions")
    op.drop_table("review_decisions")
    # ### end Alembic commands ###
