"""niches

Revision ID: fd327ec3a132
Revises: 6c65720cb496
Create Date: 2026-08-08 17:44:30.453502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd327ec3a132"
down_revision: Union[str, Sequence[str], None] = "6c65720cb496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "niches",
        sa.Column("niche_id", sa.Uuid(), nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("niche_id"),
    )
    op.create_index(op.f("ix_niches_keyword"), "niches", ["keyword"], unique=True)
    op.create_index(op.f("ix_niches_score"), "niches", ["score"], unique=False)
    op.create_index(op.f("ix_niches_scored_at"), "niches", ["scored_at"], unique=False)
    op.create_index(op.f("ix_niches_status"), "niches", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_niches_status"), table_name="niches")
    op.drop_index(op.f("ix_niches_scored_at"), table_name="niches")
    op.drop_index(op.f("ix_niches_score"), table_name="niches")
    op.drop_index(op.f("ix_niches_keyword"), table_name="niches")
    op.drop_table("niches")
    # ### end Alembic commands ###
